### ISSUE TITLE
Classpath broken on Fabric

### ISSUE THREAD

**Issue by otomir23** [Infinidoge/nix-minecraft#65]
Looks like https://github.com/Infinidoge/nix-minecraft/commit/fa037f484d8775119a5e4fb3f20aaec15c19c118 makes Fabric Loader have two instances on the classpath at once, which is an [illegal state](https://github.com/FabricMC/fabric-loader/blob/1a833267b54beea5eb635222df4af149f8a6a1d6/src/main/java/net/fabricmc/loader/impl/util/LoaderUtil.java#L50). The server fails to start. 

<details><summary>Stack trace for reference (fabric-1.20.1-0.15.11)</summary>

```
java.lang.IllegalStateException: trying to load net.fabricmc.loader.impl.FabricLoaderImpl from target class loader
        at net.fabricmc.loader.impl.util.LoaderUtil.verifyNotInTargetCl(LoaderUtil.java:55) ~[16h8ywfxn9dhw6mci6cz40yglyvp456r-fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.<clinit>(FabricLoaderImpl.java:619) ~[16h8ywfxn9dhw6mci6cz40yglyvp456r-fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.api.FabricLoader.getInstance(FabricLoader.java:42) ~[16h8ywfxn9dhw6mci6cz40yglyvp456r-fabric-loader-0.15.11.jar:?]
        at net.minecraft.class_6396.mdf82ea6$fabric-crash-report-info-v1$lambda$fillSystemDetails$0$1(class_6396.java:544) ~[server-intermediary.jar:?]
        at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[server-intermediary.jar:?]
        at net.minecraft.class_6396.handler$zzm000$fabric-crash-report-info-v1$fillSystemDetails(class_6396.java:541) ~[server-intermediary.jar:?]
        at net.minecraft.class_6396.<init>(class_6396.java:58) ~[server-intermediary.jar:?]
        at net.minecraft.class_128.<init>(class_128.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_128.method_24305(class_128.java:274) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:102) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[16h8ywfxn9dhw6mci6cz40yglyvp456r-fabric-loader-0.15.11.jar:?]
        ... 3 more
```

</details>

**Comment by Infinidoge** [comment]
Hmm. I thought that was one I explicitly tested, but nope it's broken, pain!
